# Site
repository: yanlinlin82/yanlinlin82.github.io
favicon: images/favicon.ico

# Personal info
name: Linlin Yan
title: Bioinformatics Ph.D.
email: yanlinlin82@gmail.com
website: www.github.com/yanlinlin82

# Social links
twitter_username: yanlinlin82
github_username:  yanlinlin82
# dribbble_username: yanlinlin82
facebook_username: yanlinlin82
# flickr_username: yanlinlin82
# instagram_username: yanlinlin82
linkedin_username: yanlinlin82
# pinterest_username: yanlinlin82
# youtube_username: yanlinlin82
# googleplus_username: +yanlinlin82

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Linlin and I'm a bioinformatics PhD, with 20+ years of programming experience, also an open-source advocate, interested in high-throughput sequencing, genomics and other -omics.

  I am most skilled in: <mark>C++</mark>, <mark>R</mark> and <mark>Perl</mark>

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in programming and data analysis some of my other interests and hobbies are:
  - Writing
  - Genetic counceiling

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
